version: "3.9"
services:
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: signup_login
      DB_USER: mayur
      DB_PASSWORD: mayur
  
  
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306  
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: signup_login
      MYSQL_USER: mayur
      MYSQL_PASSWORD: mayur
    
    volumes:
      - ./db_data:/var/lib/mysql

  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
volumes:
  db_data:
